version: '3.9'

services:
  workspace:
    image: web-service-gin-image
    container_name: web-service-gin-container
    build:
      context: ./
      dockerfile: ./.docker/workspace/Dockerfile
    # M1 Mac を使用している人は，以下の platform に対するコメントアウトを削除してください
    # platform: linux/x86_64
    tty: true
    ports:
      - 9001:9000
    volumes:
      - type: bind
        source: ./
        target: /home/vscode/web-service-gin
        consistency: delegated
      # - type: volume
      #   source: vendor_volume
      #   target: /var/www/html/vendor
    # depends_on:
    #   - mysql
  postgresql:
      image: postgres:15rc2-alpine
      restart: always
      environment:
        POSTGRES_USER: go-demo
        POSTGRES_PASSWORD: password
        PGPASSWORD: password123
        POSTGRES_DB: go-demo
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
        
volumes:
  postgres-data: